"""add agent_builds

Revision ID: e39e815e073d
Revises: 001
Create Date: 2026-06-15 14:44:07.666461
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e39e815e073d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_computer_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'computers', ['computer_id'], ['id'])
    op.drop_constraint(op.f('commands_computer_id_fkey'), 'commands', type_='foreignkey')
    op.drop_constraint(op.f('commands_sent_by_fkey'), 'commands', type_='foreignkey')
    op.create_foreign_key(None, 'commands', 'computers', ['computer_id'], ['id'])
    op.create_foreign_key(None, 'commands', 'users', ['sent_by'], ['id'])
    op.drop_constraint(op.f('computers_group_id_fkey'), 'computers', type_='foreignkey')
    op.create_foreign_key(None, 'computers', 'computer_groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(op.f('policies_created_by_fkey'), 'policies', type_='foreignkey')
    op.create_foreign_key(None, 'policies', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('policy_assignments_policy_id_fkey'), 'policy_assignments', type_='foreignkey')
    op.drop_constraint(op.f('policy_assignments_assigned_by_fkey'), 'policy_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'policy_assignments', 'policies', ['policy_id'], ['id'])
    op.create_foreign_key(None, 'policy_assignments', 'users', ['assigned_by'], ['id'])
    op.drop_constraint(op.f('screenshots_computer_id_fkey'), 'screenshots', type_='foreignkey')
    op.create_foreign_key(None, 'screenshots', 'computers', ['computer_id'], ['id'])
    op.drop_constraint(op.f('users_created_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_created_by_fkey'), 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.create_foreign_key(op.f('screenshots_computer_id_fkey'), 'screenshots', 'computers', ['computer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'policy_assignments', type_='foreignkey')
    op.drop_constraint(None, 'policy_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('policy_assignments_assigned_by_fkey'), 'policy_assignments', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('policy_assignments_policy_id_fkey'), 'policy_assignments', 'policies', ['policy_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.create_foreign_key(op.f('policies_created_by_fkey'), 'policies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'computers', type_='foreignkey')
    op.create_foreign_key(op.f('computers_group_id_fkey'), 'computers', 'computer_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'commands', type_='foreignkey')
    op.drop_constraint(None, 'commands', type_='foreignkey')
    op.create_foreign_key(op.f('commands_sent_by_fkey'), 'commands', 'users', ['sent_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('commands_computer_id_fkey'), 'commands', 'computers', ['computer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_computer_id_fkey'), 'audit_logs', 'computers', ['computer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
